x-env: &env
  MONGO_HOST: ${MONGO_HOST:-mongo}
  MONGO_PORT: ${MONGO_PORT:-27017}
  MONGO_USER: ${MONGO_USER:-admin}
  MONGO_PASS: ${MONGO_PASS:-admin}
  MONGO_NAME: ${MONGO_NAME:-bot}
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin}


services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      <<: *env
    volumes:
      - mongo_db:/data/db

  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    command:
      - python main.py
    environment:
      <<: *env
    # TODO: volumes rewrites copy of local.env file,
#    volumes:
#      - "/app:/code"

    depends_on:
      - mongo

volumes:
  mongo_db: