

TRAIN_TYPE_STRENGTH = 'strength'
TRAIN_TYPE_CARDIO = 'cardio'
TRAIN_TYPES = (TRAIN_TYPE_STRENGTH, TRAIN_TYPE_CARDIO)

PART_HAND = 'hand'
PART_BODY = 'body'
PART_LEG = 'leg'
PARTS = (PART_HAND, PART_BODY, PART_LEG)
